# Generated by Django 4.2.30 on 2026-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datestorage',
            name='start_cp_time',
            field=models.TimeField(null=True),
        ),
    ]
